import 'package:flutter/foundation.dart';
import '../../domain/entities/supplement.dart';
import '../../domain/entities/supplement_stack.dart';
import '../../domain/repositories/supplement_repository.dart';
import '../../domain/repositories/stack_repository.dart';
import '../../utils/logger.dart';

/// View model for the Library/Discovery screen
/// Manages supplement browsing, search, and filtering
class LibraryViewModel extends ChangeNotifier {
  final SupplementRepository _supplementRepository;
  final StackRepository _stackRepository;
  final String _userId;

  // State
  List<Supplement> _allSupplements = [];
  List<Supplement> _filteredSupplements = [];
  String _searchQuery = '';
  String? _selectedCategory;
  String? _evidenceStrength;
  bool? _stimulantCompatible;
  String? _form;
  String _currentStatus = 'beneficial';
  bool _isLoading = false;
  String? _error;
  bool _isDisposed = false;

  // Getters
  List<Supplement> get supplements => _filteredSupplements;
  List<Supplement> get allSupplements => _allSupplements;
  String get searchQuery => _searchQuery;
  String? get selectedCategory => _selectedCategory;
  String? get evidenceStrength => _evidenceStrength;
  bool? get stimulantCompatible => _stimulantCompatible;
  String? get form => _form;
  String get currentStatus => _currentStatus;
  bool get isLoading => _isLoading;
  String? get error => _error;

  /// Get unique categories from supplements
  List<String> get categories {
    final cats = <String>{};
    for (final s in _allSupplements) {
      cats.add(s.category);
    }
    return cats.toList()..sort();
  }

  LibraryViewModel({
    required SupplementRepository supplementRepository,
    required StackRepository stackRepository,
    required String userId,
  })  : _supplementRepository = supplementRepository,
        _stackRepository = stackRepository,
        _userId = userId;

  /// Initialize - load all supplements
  Future<void> initialize() async {
    _setLoading(true);
    _error = null;

    try {
      _allSupplements =
          await _supplementRepository.getAllSupplements(userId: _userId);
      _applyFilters();
    } catch (e) {
      _error = 'Failed to load supplements: $e';
      AppLogger.e(_error ?? 'Failed to load supplements');
    } finally {
      _setLoading(false);
    }
  }

  /// Create a new custom supplement
  Future<void> createCustomSupplement({
    required String name,
    required String category,
    String? dosage,
    String? timeOfDay,
    List<String> benefits = const [],
  }) async {
    _setLoading(true);
    try {
      final supplement = Supplement(
        id: '', // Will be generated by Firestore
        name: name,
        category: category,
        dosage: dosage,
        timeOfDay: timeOfDay,
        benefits: benefits,
        userId: _userId,
        isCustom: true,
        status: 'beneficial',
      );

      await _supplementRepository.saveCustomSupplement(supplement);
      await initialize(); // Refresh list
    } catch (e) {
      _error = 'Failed to create supplement: $e';
      AppLogger.e(_error ?? 'Creation failed');
    } finally {
      _setLoading(false);
    }
  }

  /// Delete a custom supplement
  Future<void> deleteCustomSupplement(String supplementId) async {
    _setLoading(true);
    try {
      await _supplementRepository.deleteCustomSupplement(supplementId, _userId);
      await initialize(); // Refresh list
    } catch (e) {
      _error = 'Failed to delete supplement: $e';
      AppLogger.e(_error ?? 'Deletion failed');
    } finally {
      _setLoading(false);
    }
  }

  /// Search supplements by query
  Future<void> search(String query) async {
    _searchQuery = query;
    _applyFilters();
  }

  /// Filter by category
  void filterByCategory(String? category) {
    _selectedCategory = category;
    _applyFilters();
  }

  /// Filter by evidence strength
  void filterByEvidence(String? strength) {
    _evidenceStrength = strength;
    _applyFilters();
  }

  /// Filter by stimulant compatibility
  void filterByStimulant(bool? compatible) {
    _stimulantCompatible = compatible;
    _applyFilters();
  }

  /// Filter by form
  void filterByForm(String? form) {
    _form = form;
    _applyFilters();
  }

  /// Filter by status (beneficial vs avoid)
  void filterByStatus(String status) {
    _currentStatus = status;
    _applyFilters();
  }

  /// Clear all filters
  void clearFilters() {
    _searchQuery = '';
    _selectedCategory = null;
    _evidenceStrength = null;
    _stimulantCompatible = null;
    _form = null;
    _currentStatus = 'beneficial';
    _applyFilters();
  }

  /// Get supplement by ID
  Supplement? getSupplement(String id) {
    try {
      return _allSupplements.firstWhere((s) => s.id == id);
    } catch (_) {
      return null;
    }
  }

  /// Add a supplement to a specific stack
  Future<void> addToStack(Supplement supplement, String stackName) async {
    _setLoading(true);
    try {
      final userStacks = await _stackRepository.getUserStacks(_userId);

      // Try to find existing stack by name
      SupplementStack? targetStack;
      try {
        targetStack = userStacks.firstWhere(
            (s) => s.name.toLowerCase().contains(stackName.toLowerCase()));
      } catch (_) {
        targetStack = null;
      }

      final slot = _getNormalizedSlot(stackName);
      final now = DateTime.now();

      if (targetStack != null) {
        // Add to existing stack
        final newItems = List<StackItem>.from(targetStack.items);

        // Prevent duplicates
        if (!newItems.any((item) => item.supplementId == supplement.id)) {
          newItems.add(StackItem(
            supplementId: supplement.id,
            order: newItems.length,
            scheduledTime: _getDefaultTimeForStack(stackName),
          ));
        }

        final updatedStack = targetStack.copyWith(
          items: newItems,
          timeOfDay: slot, // Ensure slot is standardized
          updatedAt: now,
        );
        await _stackRepository.saveStack(_userId, updatedStack);
      } else {
        // Create new stack
        final newStack = SupplementStack(
          id: '${_userId}_${slot}_$now',
          userId: _userId,
          name: stackName,
          items: [
            StackItem(
              supplementId: supplement.id,
              order: 0,
              scheduledTime: _getDefaultTimeForStack(stackName),
            )
          ],
          timeOfDay: slot,
          createdAt: now,
          updatedAt: now,
        );
        await _stackRepository.saveStack(_userId, newStack);
      }
    } catch (e) {
      _error = 'Failed to add to stack: $e';
      AppLogger.e('ERROR in addToStack', e);
      rethrow;
    } finally {
      _setLoading(false);
    }
  }

  String _getNormalizedSlot(String stackName) {
    final name = stackName.toLowerCase();
    if (name.contains('morning')) return 'morning';
    if (name.contains('afternoon')) return 'afternoon';
    if (name.contains('evening')) return 'evening';
    if (name.contains('night')) return 'night';
    return name;
  }

  String _getDefaultTimeForStack(String stackName) {
    final slot = _getNormalizedSlot(stackName);
    switch (slot) {
      case 'morning':
        return '08:00';
      case 'afternoon':
        return '14:00';
      case 'evening':
        return '20:00';
      case 'night':
        return '22:00';
      default:
        return '09:00';
    }
  }

  // Private helpers

  void _applyFilters() {
    _filteredSupplements = _allSupplements.where((s) {
      // Status filter (Primary)
      if (s.status != _currentStatus) {
        return false;
      }

      // Category filter
      if (_selectedCategory != null && s.category != _selectedCategory) {
        return false;
      }

      // Evidence filter
      if (_evidenceStrength != null &&
          s.evidenceLevel?.toLowerCase() != _evidenceStrength!.toLowerCase()) {
        return false;
      }

      // Stimulant compatibility filter
      if (_stimulantCompatible != null) {
        // Assume isPrescription = stimulant for now, or just true if matches
        // In wireframe "Stimulant Compatible" might mean isPrescription == false
        if (_stimulantCompatible! && s.isPrescription) return false;
        if (!_stimulantCompatible! && !s.isPrescription) return false;
      }

      // Form filter
      if (_form != null && s.form?.toLowerCase() != _form!.toLowerCase()) {
        return false;
      }

      // Search filter (local)
      if (_searchQuery.isNotEmpty) {
        final query = _searchQuery.toLowerCase();
        final nameMatch = s.name.toLowerCase().contains(query);
        final benefitsMatch = s.benefits.any(
          (b) => b.toLowerCase().contains(query),
        );
        if (!nameMatch && !benefitsMatch) return false;
      }

      return true;
    }).toList();

    notifyListeners();
  }

  @override
  void dispose() {
    _isDisposed = true;
    super.dispose();
  }

  @override
  void notifyListeners() {
    if (!_isDisposed) {
      super.notifyListeners();
    }
  }

  void _setLoading(bool loading) {
    _isLoading = loading;
    notifyListeners();
  }
}
