import 'package:flutter/foundation.dart';
import '../../domain/entities/supplement.dart';
import '../../domain/entities/supplement_stack.dart';
import '../../domain/repositories/supplement_repository.dart';
import '../../domain/repositories/stack_repository.dart';
import '../../domain/repositories/settings_repository.dart';
import '../../utils/logger.dart';

/// View model for the Library/Discovery screen
/// Manages supplement browsing, search, and filtering
class LibraryViewModel extends ChangeNotifier {
  final SupplementRepository _supplementRepository;
  final StackRepository _stackRepository;
  final SettingsRepository _settingsRepository;
  final String _userId;

  // State
  List<Supplement> _allSupplements = [];
  List<Supplement> _filteredSupplements = [];
  String _searchQuery = '';
  List<String> _selectedCategories = [];
  List<String> _selectedEvidenceLevels = [];
// _selectedClassAStatus removed
  List<String> _selectedForms = [];
  String _currentStatus = 'beneficial';
  bool _isLoading = false;
  String? _error = '';
  bool _isDisposed = false;

  // Getters
  List<Supplement> get supplements => _filteredSupplements;
  List<Supplement> get allSupplements => _allSupplements;
  String get searchQuery => _searchQuery;
  List<String> get selectedCategories => _selectedCategories;
  String? get selectedCategory =>
      _selectedCategories.isEmpty ? null : _selectedCategories.first;
  List<String> get selectedEvidenceLevels => _selectedEvidenceLevels;
// selectedClassAStatus removed
  List<String> get selectedForms => _selectedForms;
  String get currentStatus => _currentStatus;
  bool get isLoading => _isLoading;
  String? get error => _error;

  /// Get unique categories from supplements
  List<String> get categories {
    final cats = <String>{};
    for (final s in _allSupplements) {
      cats.add(s.category);
    }
    return cats.toList()..sort();
  }

  LibraryViewModel({
    required SupplementRepository supplementRepository,
    required StackRepository stackRepository,
    required SettingsRepository settingsRepository,
    required String userId,
  })  : _supplementRepository = supplementRepository,
        _stackRepository = stackRepository,
        _settingsRepository = settingsRepository,
        _userId = userId;

  /// Initialize - load all supplements
  Future<void> initialize() async {
    _setLoading(true);
    _error = null;

    try {
      final fetched =
          await _supplementRepository.getAllSupplements(userId: _userId);
      _allSupplements = _deduplicateSupplements(fetched);
      _applyFilters();
    } catch (e) {
      _error = 'Failed to load supplements: $e';
      AppLogger.e(_error ?? 'Failed to load supplements');
    } finally {
      _setLoading(false);
    }
  }

  /// Create a new custom supplement
  Future<void> createCustomSupplement({
    required String name,
    required String category,
    String? dosage,
    String? timeOfDay,
    List<String> benefits = const [],
    String? evidenceLevel,
// focusMedCompatibilitys param removed
    String? form,
  }) async {
    _setLoading(true);
    try {
      final supplement = Supplement(
        id: '', // Will be generated by Firestore
        name: name,
        category: category,
        dosage: dosage,
        timeOfDay: timeOfDay,
        benefits: benefits,
        evidenceLevel: evidenceLevel,
// focusMedCompatibilitys constructor argument removed
        form: form,
        userId: _userId,
        isCustom: true,
        status: 'beneficial',
      );

      await _supplementRepository.saveCustomSupplement(supplement);
      await initialize(); // Refresh list
    } catch (e) {
      _error = 'Failed to create supplement: $e';
      AppLogger.e(_error ?? 'Creation failed');
    } finally {
      _setLoading(false);
    }
  }

  /// Delete a custom supplement
  Future<void> deleteCustomSupplement(String supplementId) async {
    _setLoading(true);
    try {
      await _supplementRepository.deleteCustomSupplement(supplementId, _userId);
      await initialize(); // Refresh list
    } catch (e) {
      _error = 'Failed to delete supplement: $e';
      AppLogger.e(_error ?? 'Deletion failed');
    } finally {
      _setLoading(false);
    }
  }

  /// Search supplements by query
  Future<void> search(String query) async {
    _searchQuery = query;
    _applyFilters();
  }

  /// Filter by category (toggles selection)
  void filterByCategory(String? category) {
    if (category == null) {
      _selectedCategories = [];
    } else {
      if (_selectedCategories.contains(category)) {
        _selectedCategories.remove(category);
      } else {
        _selectedCategories.add(category);
      }
    }
    _applyFilters();
  }

  /// Filter by evidence strength (Multi-select)
  void filterByEvidence(String? strength) {
    if (strength == null) {
      _selectedEvidenceLevels = [];
    } else {
      if (_selectedEvidenceLevels.contains(strength)) {
        _selectedEvidenceLevels.remove(strength);
      } else {
        _selectedEvidenceLevels.add(strength);
      }
    }
    _applyFilters();
  }

  // filterByClassA removed

  /// Filter by form (Multi-select)
  void filterByForm(String? form) {
    if (form == null) {
      _selectedForms = [];
    } else {
      if (_selectedForms.contains(form)) {
        _selectedForms.remove(form);
      } else {
        _selectedForms.add(form);
      }
    }
    _applyFilters();
  }

  /// Filter by status (beneficial vs avoid)
  void filterByStatus(String status) {
    _currentStatus = status;
    _applyFilters();
  }

  /// Clear all filters
  void clearFilters() {
    _searchQuery = '';
    _selectedCategories = [];
    _selectedEvidenceLevels = [];
// _selectedClassAStatus reset removed
    _selectedForms = [];
    _currentStatus = 'beneficial';
    _applyFilters();
  }

  /// Get supplement by ID
  Supplement? getSupplement(String id) {
    try {
      return _allSupplements.firstWhere((s) => s.id == id);
    } catch (_) {
      return null;
    }
  }

  /// Add a supplement to a specific stack
  Future<void> addToStack(Supplement supplement, String stackName) async {
    _setLoading(true);
    try {
      final userStacks = await _stackRepository.getUserStacks(_userId);

      final slot = _getNormalizedSlot(stackName);

      // Try to find existing stack by name OR slot
      SupplementStack? targetStack;
      try {
        targetStack = userStacks.firstWhere((s) =>
            s.name.toLowerCase().contains(stackName.toLowerCase()) ||
            s.timeOfDay?.toLowerCase() == slot);
      } catch (_) {
        targetStack = null;
      }

      final now = DateTime.now();

      if (targetStack != null) {
        // Add to existing stack
        final newItems = List<StackItem>.from(targetStack.items);

        // Prevent duplicates
        if (!newItems.any((item) => item.supplementId == supplement.id)) {
          newItems.add(StackItem(
            supplementId: supplement.id,
            order: newItems.length,
            scheduledTime: _getDefaultTimeForStack(stackName),
          ));
        }

        final updatedStack = targetStack.copyWith(
          items: newItems,
          timeOfDay: slot, // Ensure slot is standardized
          updatedAt: now,
        );
        AppLogger.i(
            'Adding supplement ${supplement.name} to EXISTING stack ${targetStack.name} (id: ${targetStack.id})');
        await _stackRepository.saveStack(_userId, updatedStack);
      } else {
        // Create new stack
        AppLogger.i('Creating NEW stack $stackName for slot $slot');
        final newStack = SupplementStack(
          id: '${_userId}_${slot}_${now.millisecondsSinceEpoch}',
          userId: _userId,
          name: stackName,
          items: [
            StackItem(
              supplementId: supplement.id,
              order: 0,
              scheduledTime: _getDefaultTimeForStack(stackName),
            )
          ],
          timeOfDay: slot,
          createdAt: now,
          updatedAt: now,
        );
        await _stackRepository.saveStack(_userId, newStack);
      }
    } catch (e) {
      AppLogger.e('Error in addToStack', e);
      _error = 'Failed to add to stack: $e';
      rethrow;
    } finally {
      _setLoading(false);
    }
  }

  String _getNormalizedSlot(String stackName) {
    final name = stackName.toLowerCase();
    if (name.contains('morning')) return 'morning';
    if (name.contains('afternoon')) return 'afternoon';
    if (name.contains('evening')) return 'evening';
    if (name.contains('night')) return 'night';
    if (name.contains('startup')) return 'morning';
    if (name.contains('boost')) return 'afternoon';
    if (name.contains('recovery')) return 'night';
    return name;
  }

  String _getDefaultTimeForStack(String stackName) {
    final slot = _getNormalizedSlot(stackName);
    if (['morning', 'afternoon', 'evening', 'night'].contains(slot)) {
      final time = _settingsRepository.getSlotTime(slot);
      return '${time.hour.toString().padLeft(2, '0')}:${time.minute.toString().padLeft(2, '0')}';
    }
    return '09:00';
  }

  List<Supplement> _deduplicateSupplements(List<Supplement> supplements) {
    final Map<String, Supplement> uniqueMap = {};
    for (final s in supplements) {
      final key = s.name.toLowerCase().trim();
      // If we have a duplicate, prefer the one with more data (global usually has more)
      // or if one is already in the map, only replace if the new one is 'better'
      if (!uniqueMap.containsKey(key)) {
        uniqueMap[key] = s;
      } else {
        // Simple heuristic: prefer the one with longer description or more benefits
        final existing = uniqueMap[key]!;
        final sScore = (s.description.length) + (s.benefits.length * 10);
        final eScore =
            (existing.description.length) + (existing.benefits.length * 10);

        if (sScore > eScore) {
          uniqueMap[key] = s;
        }
      }
    }
    return uniqueMap.values.toList()
      ..sort((a, b) => a.name.toLowerCase().compareTo(b.name.toLowerCase()));
  }

  // Private helpers

  void _applyFilters() {
    _filteredSupplements = _allSupplements.where((s) {
      // Status filter (Primary)
      if (s.status != _currentStatus) {
        return false;
      }

      // Category filter (Multi-select)
      if (_selectedCategories.isNotEmpty &&
          !_selectedCategories.contains(s.category)) {
        return false;
      }

      // Evidence filter (Multi-select)
      if (_selectedEvidenceLevels.isNotEmpty) {
        if (s.evidenceLevel == null ||
            !_selectedEvidenceLevels.any(
                (e) => e.toLowerCase() == s.evidenceLevel!.toLowerCase())) {
          return false;
        }
      }

      // Class A compatibility filter REMOVED

      // Form filter (Multi-select)
      if (_selectedForms.isNotEmpty) {
        if (s.form == null ||
            !_selectedForms
                .any((f) => f.toLowerCase() == s.form!.toLowerCase())) {
          return false;
        }
      }

      // Search filter (local)
      if (_searchQuery.isNotEmpty) {
        final query = _searchQuery.toLowerCase();
        final nameMatch = s.name.toLowerCase().contains(query);
        final benefitsMatch = s.benefits.any(
          (b) => b.toLowerCase().contains(query),
        );
        if (!nameMatch && !benefitsMatch) return false;
      }

      return true;
    }).toList();

    notifyListeners();
  }

  @override
  void dispose() {
    _isDisposed = true;
    super.dispose();
  }

  @override
  void notifyListeners() {
    if (!_isDisposed) {
      super.notifyListeners();
    }
  }

  void _setLoading(bool loading) {
    _isLoading = loading;
    notifyListeners();
  }
}
