// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'dummy-api-key',
    appId: '1:123456789:web:dummy-app-id',
    messagingSenderId: '123456789',
    projectId: 'adhd-supplement-app',
    authDomain: 'adhd-supplement-app.firebaseapp.com',
    storageBucket: 'adhd-supplement-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo9QF3oAS-F4GbBEkEIOY6o230_jZRBlg',
    appId: '1:93466359350:android:624499d319cae893f20a97',
    messagingSenderId: '93466359350',
    projectId: 'adhd-supplement-app',
    storageBucket: 'adhd-supplement-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLTcPuiQcaVjmQqAyFT6VJiTQ-WWC4m7w',
    appId: '1:93466359350:ios:ea28d62154476bd3f20a97',
    messagingSenderId: '93466359350',
    projectId: 'adhd-supplement-app',
    storageBucket: 'adhd-supplement-app.firebasestorage.app',
    iosBundleId: 'com.example.adhdSupplementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLTcPuiQcaVjmQqAyFT6VJiTQ-WWC4m7w',
    appId: '1:93466359350:ios:ea28d62154476bd3f20a97',
    messagingSenderId: '93466359350',
    projectId: 'adhd-supplement-app',
    storageBucket: 'adhd-supplement-app.firebasestorage.app',
    iosBundleId: 'com.example.adhdSupplementApp',
  );

}