// Mocks generated by Mockito 5.4.6 from annotations
// in adhd_supplement_app/test/presentation/library_to_dashboard_sync_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:adhd_supplement_app/domain/entities/supplement.dart' as _i4;
import 'package:adhd_supplement_app/domain/entities/supplement_stack.dart'
    as _i6;
import 'package:adhd_supplement_app/domain/repositories/stack_repository.dart'
    as _i5;
import 'package:adhd_supplement_app/domain/repositories/supplement_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SupplementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupplementRepository extends _i1.Mock
    implements _i2.SupplementRepository {
  @override
  _i3.Future<List<_i4.Supplement>> getAllSupplements({String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSupplements,
          [],
          {#userId: userId},
        ),
        returnValue: _i3.Future<List<_i4.Supplement>>.value(<_i4.Supplement>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Supplement>>.value(<_i4.Supplement>[]),
      ) as _i3.Future<List<_i4.Supplement>>);

  @override
  _i3.Future<List<_i4.Supplement>> getSupplementsByCategory(
    String? category, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSupplementsByCategory,
          [category],
          {#userId: userId},
        ),
        returnValue: _i3.Future<List<_i4.Supplement>>.value(<_i4.Supplement>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Supplement>>.value(<_i4.Supplement>[]),
      ) as _i3.Future<List<_i4.Supplement>>);

  @override
  _i3.Future<List<_i4.Supplement>> searchSupplements(
    String? query, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchSupplements,
          [query],
          {#userId: userId},
        ),
        returnValue: _i3.Future<List<_i4.Supplement>>.value(<_i4.Supplement>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Supplement>>.value(<_i4.Supplement>[]),
      ) as _i3.Future<List<_i4.Supplement>>);

  @override
  _i3.Future<_i4.Supplement?> getSupplement(
    String? id, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSupplement,
          [id],
          {#userId: userId},
        ),
        returnValue: _i3.Future<_i4.Supplement?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.Supplement?>.value(),
      ) as _i3.Future<_i4.Supplement?>);

  @override
  _i3.Stream<List<_i4.Supplement>> watchSupplements({String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchSupplements,
          [],
          {#userId: userId},
        ),
        returnValue: _i3.Stream<List<_i4.Supplement>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i4.Supplement>>.empty(),
      ) as _i3.Stream<List<_i4.Supplement>>);

  @override
  _i3.Future<void> saveCustomSupplement(_i4.Supplement? supplement) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCustomSupplement,
          [supplement],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCustomSupplement(
    String? id,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCustomSupplement,
          [
            id,
            userId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> trackReferralClick(String? supplementId) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackReferralClick,
          [supplementId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [StackRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStackRepository extends _i1.Mock implements _i5.StackRepository {
  @override
  _i3.Future<void> saveStack(
    String? userId,
    _i6.SupplementStack? stack,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveStack,
          [
            userId,
            stack,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i6.SupplementStack?> getStack(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStack,
          [userId],
        ),
        returnValue: _i3.Future<_i6.SupplementStack?>.value(),
        returnValueForMissingStub: _i3.Future<_i6.SupplementStack?>.value(),
      ) as _i3.Future<_i6.SupplementStack?>);

  @override
  _i3.Future<List<_i6.SupplementStack>> getUserStacks(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserStacks,
          [userId],
        ),
        returnValue: _i3.Future<List<_i6.SupplementStack>>.value(
            <_i6.SupplementStack>[]),
        returnValueForMissingStub: _i3.Future<List<_i6.SupplementStack>>.value(
            <_i6.SupplementStack>[]),
      ) as _i3.Future<List<_i6.SupplementStack>>);

  @override
  _i3.Stream<List<_i6.SupplementStack>> watchUserStacks(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchUserStacks,
          [userId],
        ),
        returnValue: _i3.Stream<List<_i6.SupplementStack>>.empty(),
        returnValueForMissingStub:
            _i3.Stream<List<_i6.SupplementStack>>.empty(),
      ) as _i3.Stream<List<_i6.SupplementStack>>);
}
