// Mocks generated by Mockito 5.4.6 from annotations
// in adhd_supplement_app/test/unit/application/view_models/article_detail_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:adhd_supplement_app/domain/entities/article.dart' as _i4;
import 'package:adhd_supplement_app/domain/repositories/article_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ArticleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleRepository extends _i1.Mock implements _i2.ArticleRepository {
  MockArticleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Article?> getArticle(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getArticle,
          [id],
        ),
        returnValue: _i3.Future<_i4.Article?>.value(),
      ) as _i3.Future<_i4.Article?>);

  @override
  _i3.Future<List<_i4.Article>> getRelatedArticles(String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRelatedArticles,
          [articleId],
        ),
        returnValue: _i3.Future<List<_i4.Article>>.value(<_i4.Article>[]),
      ) as _i3.Future<List<_i4.Article>>);

  @override
  _i3.Future<List<_i4.Article>> getArticles() => (super.noSuchMethod(
        Invocation.method(
          #getArticles,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Article>>.value(<_i4.Article>[]),
      ) as _i3.Future<List<_i4.Article>>);

  @override
  _i3.Future<_i4.Article?> getArticleOfTheDay() => (super.noSuchMethod(
        Invocation.method(
          #getArticleOfTheDay,
          [],
        ),
        returnValue: _i3.Future<_i4.Article?>.value(),
      ) as _i3.Future<_i4.Article?>);
}
