// Mocks generated by Mockito 5.4.6 from annotations
// in adhd_supplement_app/test/unit/application/view_models/doctor_export_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i8;

import 'package:adhd_supplement_app/domain/entities/daily_log.dart' as _i5;
import 'package:adhd_supplement_app/domain/entities/user.dart' as _i2;
import 'package:adhd_supplement_app/domain/repositories/auth_repository.dart'
    as _i6;
import 'package:adhd_supplement_app/domain/repositories/log_repository.dart'
    as _i3;
import 'package:adhd_supplement_app/infrastructure/services/report_pdf_service.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LogRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogRepository extends _i1.Mock implements _i3.LogRepository {
  MockLogRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.DailyLog>> getLogsByDateRange(
    String? userId,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLogsByDateRange,
          [
            userId,
            start,
            end,
          ],
        ),
        returnValue: _i4.Future<List<_i5.DailyLog>>.value(<_i5.DailyLog>[]),
      ) as _i4.Future<List<_i5.DailyLog>>);

  @override
  _i4.Future<_i5.DailyLog?> getLogForDate(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLogForDate,
          [
            userId,
            date,
          ],
        ),
        returnValue: _i4.Future<_i5.DailyLog?>.value(),
      ) as _i4.Future<_i5.DailyLog?>);

  @override
  _i4.Future<void> saveLog(_i5.DailyLog? log) => (super.noSuchMethod(
        Invocation.method(
          #saveLog,
          [log],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> getStreakCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getStreakCount,
          [userId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.DailyLog>> getRecentLogs(
    String? userId,
    int? days,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentLogs,
          [
            userId,
            days,
          ],
        ),
        returnValue: _i4.Future<List<_i5.DailyLog>>.value(<_i5.DailyLog>[]),
      ) as _i4.Future<List<_i5.DailyLog>>);

  @override
  _i4.Stream<_i5.DailyLog?> watchTodayLog(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchTodayLog,
          [userId],
        ),
        returnValue: _i4.Stream<_i5.DailyLog?>.empty(),
      ) as _i4.Stream<_i5.DailyLog?>);

  @override
  _i4.Future<void> clearAllLogs(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #clearAllLogs,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i6.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i2.User?>.value(),
      ) as _i4.Future<_i2.User?>);

  @override
  _i4.Future<_i2.User> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #signInWithEmail,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.User>);

  @override
  _i4.Future<_i2.User> signUpWithEmail(
    String? email,
    String? password,
    String? displayName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmail,
          [
            email,
            password,
            displayName,
          ],
        ),
        returnValue: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #signUpWithEmail,
            [
              email,
              password,
              displayName,
            ],
          ),
        )),
      ) as _i4.Future<_i2.User>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<_i2.User?> authStateChanges() => (super.noSuchMethod(
        Invocation.method(
          #authStateChanges,
          [],
        ),
        returnValue: _i4.Stream<_i2.User?>.empty(),
      ) as _i4.Stream<_i2.User?>);

  @override
  _i4.Future<void> updateUserProfile(_i2.User? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.User> signInAnonymously() => (super.noSuchMethod(
        Invocation.method(
          #signInAnonymously,
          [],
        ),
        returnValue: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #signInAnonymously,
            [],
          ),
        )),
      ) as _i4.Future<_i2.User>);

  @override
  _i4.Future<void> deleteUser() => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ReportPdfService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportPdfService extends _i1.Mock implements _i7.ReportPdfService {
  MockReportPdfService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i8.Uint8List> generateReport({
    required DateTime? startDate,
    required DateTime? endDate,
    required List<_i5.DailyLog>? logs,
    required double? consistency,
    required double? avgFocus,
    required double? avgMood,
    bool? includeConsistency = true,
    bool? includeFocus = true,
    bool? includeInteractions = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateReport,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #logs: logs,
            #consistency: consistency,
            #avgFocus: avgFocus,
            #avgMood: avgMood,
            #includeConsistency: includeConsistency,
            #includeFocus: includeFocus,
            #includeInteractions: includeInteractions,
          },
        ),
        returnValue: _i4.Future<_i8.Uint8List>.value(_i8.Uint8List(0)),
      ) as _i4.Future<_i8.Uint8List>);
}
