// Mocks generated by Mockito 5.4.6 from annotations
// in neurostack_app/test/unit/application/view_models/focus_checkin_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:neurostack_app/domain/entities/daily_state_checkin.dart' as _i4;
import 'package:neurostack_app/domain/repositories/checkin_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CheckInRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckInRepository extends _i1.Mock implements _i2.CheckInRepository {
  MockCheckInRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> logCheckIn(_i4.DailyStateCheckIn? checkIn) =>
      (super.noSuchMethod(
        Invocation.method(
          #logCheckIn,
          [checkIn],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.DailyStateCheckIn>> getCheckIns(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCheckIns,
          [userId],
        ),
        returnValue: _i3.Future<List<_i4.DailyStateCheckIn>>.value(
            <_i4.DailyStateCheckIn>[]),
      ) as _i3.Future<List<_i4.DailyStateCheckIn>>);

  @override
  _i3.Future<List<_i4.DailyStateCheckIn>> getCheckInsByDateRange(
    String? userId,
    DateTime? startDate,
    DateTime? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCheckInsByDateRange,
          [
            userId,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i3.Future<List<_i4.DailyStateCheckIn>>.value(
            <_i4.DailyStateCheckIn>[]),
      ) as _i3.Future<List<_i4.DailyStateCheckIn>>);

  @override
  _i3.Future<_i4.DailyStateCheckIn?> getLatestCheckIn(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestCheckIn,
          [userId],
        ),
        returnValue: _i3.Future<_i4.DailyStateCheckIn?>.value(),
      ) as _i3.Future<_i4.DailyStateCheckIn?>);

  @override
  _i3.Future<bool> hasCheckedInToday(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #hasCheckedInToday,
          [userId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteCheckIn(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCheckIn,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
