// Mocks generated by Mockito 5.4.6 from annotations
// in adhd_supplement_app/test/unit/application/view_models/history_log_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:adhd_supplement_app/domain/entities/daily_log.dart' as _i4;
import 'package:adhd_supplement_app/domain/entities/supplement_stack.dart'
    as _i6;
import 'package:adhd_supplement_app/domain/repositories/log_repository.dart'
    as _i2;
import 'package:adhd_supplement_app/domain/repositories/stack_repository.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LogRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogRepository extends _i1.Mock implements _i2.LogRepository {
  MockLogRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.DailyLog>> getLogsByDateRange(
    String? userId,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLogsByDateRange,
          [
            userId,
            start,
            end,
          ],
        ),
        returnValue: _i3.Future<List<_i4.DailyLog>>.value(<_i4.DailyLog>[]),
      ) as _i3.Future<List<_i4.DailyLog>>);

  @override
  _i3.Future<_i4.DailyLog?> getLogForDate(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLogForDate,
          [
            userId,
            date,
          ],
        ),
        returnValue: _i3.Future<_i4.DailyLog?>.value(),
      ) as _i3.Future<_i4.DailyLog?>);

  @override
  _i3.Future<void> saveLog(_i4.DailyLog? log) => (super.noSuchMethod(
        Invocation.method(
          #saveLog,
          [log],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getStreakCount(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getStreakCount,
          [userId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.DailyLog>> getRecentLogs(
    String? userId,
    int? days,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentLogs,
          [
            userId,
            days,
          ],
        ),
        returnValue: _i3.Future<List<_i4.DailyLog>>.value(<_i4.DailyLog>[]),
      ) as _i3.Future<List<_i4.DailyLog>>);

  @override
  _i3.Stream<_i4.DailyLog?> watchTodayLog(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchTodayLog,
          [userId],
        ),
        returnValue: _i3.Stream<_i4.DailyLog?>.empty(),
      ) as _i3.Stream<_i4.DailyLog?>);

  @override
  _i3.Future<void> clearAllLogs(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #clearAllLogs,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [StackRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStackRepository extends _i1.Mock implements _i5.StackRepository {
  MockStackRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveStack(
    String? userId,
    _i6.SupplementStack? stack,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveStack,
          [
            userId,
            stack,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i6.SupplementStack?> getStack(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStack,
          [userId],
        ),
        returnValue: _i3.Future<_i6.SupplementStack?>.value(),
      ) as _i3.Future<_i6.SupplementStack?>);

  @override
  _i3.Future<List<_i6.SupplementStack>> getUserStacks(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserStacks,
          [userId],
        ),
        returnValue: _i3.Future<List<_i6.SupplementStack>>.value(
            <_i6.SupplementStack>[]),
      ) as _i3.Future<List<_i6.SupplementStack>>);

  @override
  _i3.Stream<List<_i6.SupplementStack>> watchUserStacks(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchUserStacks,
          [userId],
        ),
        returnValue: _i3.Stream<List<_i6.SupplementStack>>.empty(),
      ) as _i3.Stream<List<_i6.SupplementStack>>);
}
