// Mocks generated by Mockito 5.4.6 from annotations
// in neurostack_app/test/unit/application/view_models/stack_builder_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:neurostack_app/application/view_models/routine_safety_view_model.dart'
    as _i7;
import 'package:neurostack_app/domain/entities/supplement.dart' as _i6;
import 'package:neurostack_app/domain/entities/supplement_compatibility.dart'
    as _i9;
import 'package:neurostack_app/domain/entities/supplement_stack.dart' as _i4;
import 'package:neurostack_app/domain/repositories/stack_repository.dart'
    as _i2;
import 'package:neurostack_app/domain/repositories/supplement_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [StackRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStackRepository extends _i1.Mock implements _i2.StackRepository {
  MockStackRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveStack(
    String? userId,
    _i4.SupplementStack? stack,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveStack,
          [
            userId,
            stack,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.SupplementStack?> getStack(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStack,
          [userId],
        ),
        returnValue: _i3.Future<_i4.SupplementStack?>.value(),
      ) as _i3.Future<_i4.SupplementStack?>);

  @override
  _i3.Future<List<_i4.SupplementStack>> getUserStacks(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserStacks,
          [userId],
        ),
        returnValue: _i3.Future<List<_i4.SupplementStack>>.value(
            <_i4.SupplementStack>[]),
      ) as _i3.Future<List<_i4.SupplementStack>>);

  @override
  _i3.Stream<List<_i4.SupplementStack>> watchUserStacks(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchUserStacks,
          [userId],
        ),
        returnValue: _i3.Stream<List<_i4.SupplementStack>>.empty(),
      ) as _i3.Stream<List<_i4.SupplementStack>>);
}

/// A class which mocks [SupplementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupplementRepository extends _i1.Mock
    implements _i5.SupplementRepository {
  MockSupplementRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<void> get onCacheInvalidated => (super.noSuchMethod(
        Invocation.getter(#onCacheInvalidated),
        returnValue: _i3.Stream<void>.empty(),
      ) as _i3.Stream<void>);

  @override
  _i3.Future<List<_i6.Supplement>> getAllSupplements({String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllSupplements,
          [],
          {#userId: userId},
        ),
        returnValue: _i3.Future<List<_i6.Supplement>>.value(<_i6.Supplement>[]),
      ) as _i3.Future<List<_i6.Supplement>>);

  @override
  _i3.Future<List<_i6.Supplement>> getSupplementsByCategory(
    String? category, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSupplementsByCategory,
          [category],
          {#userId: userId},
        ),
        returnValue: _i3.Future<List<_i6.Supplement>>.value(<_i6.Supplement>[]),
      ) as _i3.Future<List<_i6.Supplement>>);

  @override
  _i3.Future<List<_i6.Supplement>> searchSupplements(
    String? query, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchSupplements,
          [query],
          {#userId: userId},
        ),
        returnValue: _i3.Future<List<_i6.Supplement>>.value(<_i6.Supplement>[]),
      ) as _i3.Future<List<_i6.Supplement>>);

  @override
  _i3.Future<_i6.Supplement?> getSupplement(
    String? id, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSupplement,
          [id],
          {#userId: userId},
        ),
        returnValue: _i3.Future<_i6.Supplement?>.value(),
      ) as _i3.Future<_i6.Supplement?>);

  @override
  _i3.Stream<List<_i6.Supplement>> watchSupplements({String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchSupplements,
          [],
          {#userId: userId},
        ),
        returnValue: _i3.Stream<List<_i6.Supplement>>.empty(),
      ) as _i3.Stream<List<_i6.Supplement>>);

  @override
  _i3.Future<void> saveCustomSupplement(_i6.Supplement? supplement) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCustomSupplement,
          [supplement],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCustomSupplement(
    String? id,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCustomSupplement,
          [
            id,
            userId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> trackReferralClick(String? supplementId) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackReferralClick,
          [supplementId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> downloadLibrary() => (super.noSuchMethod(
        Invocation.method(
          #downloadLibrary,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [RoutineSafetyViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoutineSafetyViewModel extends _i1.Mock
    implements _i7.RoutineSafetyViewModel {
  MockRoutineSafetyViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get userId => (super.noSuchMethod(
        Invocation.getter(#userId),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#userId),
        ),
      ) as String);

  @override
  List<_i9.SupplementCompatibility> get currentCompatibilitys =>
      (super.noSuchMethod(
        Invocation.getter(#currentCompatibilitys),
        returnValue: <_i9.SupplementCompatibility>[],
      ) as List<_i9.SupplementCompatibility>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasCriticalCompatibilitys => (super.noSuchMethod(
        Invocation.getter(#hasCriticalCompatibilitys),
        returnValue: false,
      ) as bool);

  @override
  List<String> get recommendations => (super.noSuchMethod(
        Invocation.getter(#recommendations),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> checkCompatibilitys(List<String>? supplementIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkCompatibilitys,
          [supplementIds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> overrideCompatibility(
    String? compatibilityId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #overrideCompatibility,
          [
            compatibilityId,
            reason,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );
}
