// Mocks generated by Mockito 5.4.6 from annotations
// in adhd_supplement_app/test/unit/application/view_models/streak_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:adhd_supplement_app/domain/entities/daily_log.dart' as _i4;
import 'package:adhd_supplement_app/domain/entities/streak.dart' as _i2;
import 'package:adhd_supplement_app/domain/repositories/streak_repository.dart'
    as _i5;
import 'package:adhd_supplement_app/infrastructure/services/streak_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStreak_0 extends _i1.SmartFake implements _i2.Streak {
  _FakeStreak_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StreakService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreakService extends _i1.Mock implements _i3.StreakService {
  MockStreakService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Streak calculateStreak({
    required _i2.Streak? currentStreak,
    required List<_i4.DailyLog>? recentLogs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateStreak,
          [],
          {
            #currentStreak: currentStreak,
            #recentLogs: recentLogs,
          },
        ),
        returnValue: _FakeStreak_0(
          this,
          Invocation.method(
            #calculateStreak,
            [],
            {
              #currentStreak: currentStreak,
              #recentLogs: recentLogs,
            },
          ),
        ),
      ) as _i2.Streak);

  @override
  bool shouldApplyGraceDay({
    required _i2.Streak? streak,
    required DateTime? missedDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shouldApplyGraceDay,
          [],
          {
            #streak: streak,
            #missedDate: missedDate,
          },
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.Streak resetGraceDays(
    _i2.Streak? streak, {
    int? graceDaysPerMonth = 2,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetGraceDays,
          [streak],
          {#graceDaysPerMonth: graceDaysPerMonth},
        ),
        returnValue: _FakeStreak_0(
          this,
          Invocation.method(
            #resetGraceDays,
            [streak],
            {#graceDaysPerMonth: graceDaysPerMonth},
          ),
        ),
      ) as _i2.Streak);
}

/// A class which mocks [StreakRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreakRepository extends _i1.Mock implements _i5.StreakRepository {
  MockStreakRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Streak?> getStreak(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getStreak,
          [userId],
        ),
        returnValue: _i6.Future<_i2.Streak?>.value(),
      ) as _i6.Future<_i2.Streak?>);

  @override
  _i6.Future<void> saveStreak(_i2.Streak? streak) => (super.noSuchMethod(
        Invocation.method(
          #saveStreak,
          [streak],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<_i2.Streak?> watchStreak(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #watchStreak,
          [userId],
        ),
        returnValue: _i6.Stream<_i2.Streak?>.empty(),
      ) as _i6.Stream<_i2.Streak?>);
}
