// Mocks generated by Mockito 5.4.6 from annotations
// in adhd_supplement_app/test/unit/application/view_models/supplement_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:adhd_supplement_app/domain/entities/supplement.dart' as _i4;
import 'package:adhd_supplement_app/domain/repositories/supplement_repository.dart'
    as _i2;
import 'package:adhd_supplement_app/infrastructure/services/url_service.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SupplementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupplementRepository extends _i1.Mock
    implements _i2.SupplementRepository {
  MockSupplementRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Supplement>> getAllSupplements() => (super.noSuchMethod(
        Invocation.method(
          #getAllSupplements,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Supplement>>.value(<_i4.Supplement>[]),
      ) as _i3.Future<List<_i4.Supplement>>);

  @override
  _i3.Future<List<_i4.Supplement>> getSupplementsByCategory(String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSupplementsByCategory,
          [category],
        ),
        returnValue: _i3.Future<List<_i4.Supplement>>.value(<_i4.Supplement>[]),
      ) as _i3.Future<List<_i4.Supplement>>);

  @override
  _i3.Future<List<_i4.Supplement>> searchSupplements(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchSupplements,
          [query],
        ),
        returnValue: _i3.Future<List<_i4.Supplement>>.value(<_i4.Supplement>[]),
      ) as _i3.Future<List<_i4.Supplement>>);

  @override
  _i3.Future<_i4.Supplement?> getSupplement(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getSupplement,
          [id],
        ),
        returnValue: _i3.Future<_i4.Supplement?>.value(),
      ) as _i3.Future<_i4.Supplement?>);

  @override
  _i3.Stream<List<_i4.Supplement>> watchSupplements() => (super.noSuchMethod(
        Invocation.method(
          #watchSupplements,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.Supplement>>.empty(),
      ) as _i3.Stream<List<_i4.Supplement>>);

  @override
  _i3.Future<void> trackReferralClick(String? supplementId) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackReferralClick,
          [supplementId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [UrlService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUrlService extends _i1.Mock implements _i5.UrlService {
  MockUrlService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> launchReferral(String? url) => (super.noSuchMethod(
        Invocation.method(
          #launchReferral,
          [url],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
